from pathlib import Path
import json,csv,hashlib,shutil,sys
repo=Path(sys.argv[1]).resolve();p=repo/'seo-audit/2026-09-08';origin='https://docs.kujolang.ai' if repo.name=='docs.kujolang.ai' else 'https://kujolang.ai';docs='docs.' in origin
na='NOT AVAILABLE — DATA ACCESS REQUIRED'
def write(name,rows,fields=None):
 if fields is None:fields=next(csv.reader((p/name).open()))
 with (p/name).open('w',newline='') as f:
  w=csv.DictWriter(f,fieldnames=fields,extrasaction='ignore');w.writeheader();w.writerows(rows)
b=json.loads((p/'baseline-summary.json').read_text());a=json.loads((p/'after-summary.json').read_text());rows=list(csv.DictReader((p/'after.csv').open()));
write('keyword-map.csv',[dict(phase='after',url=r['url'],primary_topic=r['h1'],primary_entity='Kujo',search_intent='Learn a task and find authoritative source' if docs else 'Evaluate and select a Kujo capability',primary_query_theme=r['h1'],secondary_queries='HyperFrames video skills; ElevenLabs voice selection' if 'skill' in r['url'] else r['title'],related_entities='Kujo Skills; HyperFrames; ElevenLabs' if 'skill' in r['url'] else 'Kujo ecosystem',relevant_questions='How do I use '+r['h1']+'?',competing_internal_url='No source-confirmed competing route',content_gap='Editorial mapping hypothesis; no search-volume inference',recommended_action='Measure real queries when data access is provided') for r in rows])
issues=[]
def issue(id,category,severity,urls,count,evidence,action):
 for phase in ['baseline','after']:issues.append(dict(id=id,phase=phase,category=category,severity=severity,affected_urls=urls,affected_count=count,evidence=evidence,expected_benefit='Accurate discovery and usable guidance' if category!='performance' else 'Reduce forced layout during catalog initialization',confidence='High',difficulty='Low',recommended_action=action,owner='Kujo site maintainers',status='open' if phase=='baseline' else 'fixed'))
if docs:issue('DOCS-SKILLS-01','content','P1',origin+'/collections/skills/; '+origin+'/collections/video-skills/',2,'Versioned release v0.7.0; baseline/after HTML; content/collections/*.md','Document release scope, install, all ten prompts, narrator overrides and workflow boundaries.')
if docs:issue('DOCS-MOBILE-01','responsive layout','P2',origin+'/collections/video-skills/',1,'browser-review.json: 390px viewport overflow reduced from 508px to 379px','Contain wide tables with horizontal scrolling.')
else:
 issue('SITE-SKILLS-01','content/currentness','P1',origin+'/ecosystem/skills/ and skill detail pages',136,'release-catalog-verification.json; baseline 96 skill pages versus release 135','Sync the entire version-pinned skills catalog, preserving workflow pages.')
 issue('SITE-SKILLS-02','metadata','P1',origin+'/ecosystem/skills/',1,'Frozen baseline advertises 84 despite 96 routes; build.kujo and templates/page-skills.html','Derive visible and meta-description counts from generated items.')
 issue('SITE-PERF-01','performance','P2',origin+'/ecosystem/skills/',1,'Lighthouse baseline forced-reflow insight points to site.js font read inside DOM-writing loop; source diff','Batch computed-font reads before DOM wrappers; preserve motion and compare lab metrics.')
issues = [r for r in issues if not (r['id'] == 'DOCS-MOBILE-01' and r['phase'] == 'baseline')]
write('issues.csv',issues)
perf=[]
for phase in ['baseline','after']:
 for f in sorted((p/'raw').glob(f'lighthouse-{phase}-*.json')):
  j=json.loads(f.read_text());au=j.get('audits',{});network=au.get('network-requests',{}).get('details',{}).get('items',[])
  weight=lambda typ:sum(x.get('transferSize',0) for x in network if x.get('resourceType') in typ)
  perf.append(dict(phase=phase,url=j.get('finalDisplayedUrl',j.get('finalUrl')),template=f.stem.split('-')[-1],run_date=j.get('fetchTime'),environment='Lighthouse default mobile emulation; local Chrome; shared Mac host and variable load',lighthouse_version=j.get('lighthouseVersion'),html_bytes=weight(['Document']),css_bytes=weight(['Stylesheet']),js_bytes=weight(['Script']),image_bytes=weight(['Image']),font_bytes=weight(['Font']),requests=len(network),lcp_ms=au.get('largest-contentful-paint',{}).get('numericValue',na),inp_ms=na,cls=au.get('cumulative-layout-shift',{}).get('numericValue',na),ttfb_ms=au.get('server-response-time',{}).get('numericValue',na),source=str(f.relative_to(p)),notes='Lab only. No causal or field-CWV claim. '+str(j.get('runtimeError') or 'Successful run.')))
write('performance.csv',perf)
# Authoritative live status counts are independent of the filesystem crawler.
prod={}
for phase in ['baseline','after']:
 f=p/'raw/live'/f'{phase}-full-crawl.json'
 if f.exists():
  j=json.loads(f.read_text());canon=[u for u in j['pages'] if '/cdn-cgi/' not in u];prod[phase]={'observed_urls':len(j['pages']),'canonical_content_200':sum(j['pages'][u]['status']==200 for u in canon),'non200':{u:r['status'] for u,r in j['pages'].items() if r['status']!=200},'receipt':str(f.relative_to(p))}
(p/'production-summary.json').write_text(json.dumps(prod,indent=2)+'\n')
keys=['canonical_pages','indexable_pages','missing_titles','duplicate_titles','missing_descriptions','duplicate_descriptions','missing_canonicals','h1_issues','broken_internal_links','orphan_pages','pages_deeper_than_three_clicks','missing_alt','missing_dimensions','schema_parse_errors','schema_coverage_pages','missing_responsive_candidates']
comparison='# Before and after\n\nAudit: 2026-09-08. Technical measurements only.\n\n| Metric | Baseline | After |\n| --- | ---: | ---: |\n'+''.join(f'| {k} | {b[k]} | {a[k]} |\n' for k in keys)
comparison+=f'\nP0: 0 → 0. P1: {1 if docs else 2} → 0. '+('One intentional new video guide; no canonical content removed.' if docs else '39 intentional new skills pages: 96 → 135; no existing canonical content removed.')+'\n\nInternal SEO/AI-readiness composite scores: not calculated. No fabricated score substitutes for unavailable field, ranking or citation evidence. Lighthouse observations are in performance.csv; these are not search platform scores.\n'
(p/'before-after.md').write_text(comparison)
changes='Added video style/setup guide and contextual links; updated the skills collection to v0.7.0/135 skills; contained wide tables on mobile.' if docs else 'Synced 135 skills from v0.7.0; added 39 pages and social cards; pinned source links and complete installation commands; preserved workflows; added curated video examples and docs links; replaced hard-coded counts; batched font reads before text decoration.'
(p/'changes.md').write_text('# Changes\n\n'+changes+'\n\nChanges are supported by release-catalog verification, source commits, generated after crawl, native validation, and production receipts. Reused owned assets; no new claims of hosted runtime enforcement or provider access.\n')
(p/'unresolved.md').write_text('# Unresolved measurement and access items\n\n'+na+' for authenticated search/analytics/logs, field Core Web Vitals and independent AI benchmarks. No rankings, traffic or citations are claimed to have improved.\n\nSome external URLs return 403 or time out to automated requests; these remain blocked/indeterminate rather than confirmed broken. See external-links.csv. Production /cdn-cgi/l/email-protection is an edge helper, not an indexable content route. Complete error URL counts require edge/origin logs. Training policy was preserved.\n\nLab performance is sensitive to shared host load and should be repeated alongside field measurement; do not interpret the score delta as proof of real-user improvement. No unresolved repository P0/P1 issue is concealed by these limitations.\n')
(p/'executive-summary.md').write_text(f'# SEO and AI-search audit — {origin}\n\nAudit date: 2026-09-08.\n\n## Status\n\nPASS WITH RECOMMENDATIONS. Final deployment receipts are recorded in after-provenance.json and production-summary.json.\n\n## Outcome\n\n{changes}\n\nThe untouched pinned CI baseline contains {b["canonical_pages"]} canonical pages. The after build contains {a["canonical_pages"]}. See before-after.md for exact error counts and page additions, issues.csv for root causes, and the Git history for changed files. The release itself is source-backed; claimed user benefits are limited to accurate discovery and usable examples.\n\n## Verification\n\nFull generated crawl, sitemap/HTML-link discovery, metadata, headings, canonical routes, internal links, images, JSON-LD and native repository contracts. Separate production crawls, redirects, robots, sitemap, crawler-user-agent probes, external links and mobile Lighthouse receipts. Baseline archive and per-file hashes were sealed before source edits. Deployment and runtime provenance are recorded separately from local diagnostic attempts.\n\n## Limits and next measurements\n\nAuthenticated visibility, field CWV, search-console coverage and controlled AI citations: {na}. Search observations do not establish rank or absence from an index. No composite SEO or AI-readiness score is invented. Follow the 7/28/60/90-day plan in recommendations.md.\n')
print(repo.name,b['canonical_pages'],a['canonical_pages'],a['issue_counts'])
